AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  DynamoBooksTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: books
      PrimaryKey:
        Name: id
        Type: String
    Metadata:
      SamResourceId: DynamoBooksTable
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://ssa-sam-app-poc/0ae5d9de0761eaeb30ab3cb680c50859
      Handler: helloworld.lambdaHandler
      Runtime: nodejs16.x
      Architectures:
      - x86_64
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /hello
            Method: get
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
        - app.ts
      SamResourceId: HelloWorldFunction
