version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-app-poc-stack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1p2watkxm6cn7"
s3_prefix = "sam-app-poc-stack"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
